modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/${curse_slug}"
logoFile=""
credits="Made with Forge and love"
authors="${mod_authors}"
mixinConfigs = "stardew.mixins.json"

description='''
${mod_description}
'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="flib"
    mandatory=true
    versionRange="[${flib_version},)"
    ordering="NONE"
    side="BOTH"

	